# Generated by Django 6.0.5 on 2026-05-07 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_hearing_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hearing',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='party',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_set', to='cases.case'),
        ),
    ]
