# Generated by Django 6.0.5 on 2026-05-13 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_hearing_case_alter_party_case'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(choices=[('Registry', 'Registry'), ('Judge Chambers', 'Judge Chambers'), ('Magistrate Chambers', 'Magistrate Chambers'), ('Typist Office', 'Typist Office'), ('Deputy Registrar', 'Deputy Registrar'), ('Registrar', 'Registrar'), ('Accounts', 'Accounts'), ('Advocate', 'Advocate'), ('Other', 'Other')], max_length=100)),
                ('to_location', models.CharField(choices=[('Registry', 'Registry'), ('Judge Chambers', 'Judge Chambers'), ('Magistrate Chambers', 'Magistrate Chambers'), ('Typist Office', 'Typist Office'), ('Deputy Registrar', 'Deputy Registrar'), ('Registrar', 'Registrar'), ('Accounts', 'Accounts'), ('Advocate', 'Advocate'), ('Other', 'Other')], max_length=100)),
                ('purpose', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('In Transit', 'In Transit'), ('Received', 'Received'), ('Returned', 'Returned')], default='In Transit', max_length=20)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='cases.case')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_by', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
