# Generated by Django 6.0.5 on 2026-05-13 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_filemovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Judge', 'Judge'), ('Magistrate', 'Magistrate'), ('Clerk', 'Clerk'), ('Advocate', 'Advocate'), ('Registrar', 'Registrar'), ('Deputy Registrar', 'Deputy Registrar'), ('Accounts', 'Accounts')], max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
